<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>dev.masterflomaster1</groupId>
    <artifactId>jfxcrypto</artifactId>
    <version>4.5.0</version>
    <packaging>pom</packaging>

    <name>JFXCrypto</name>
    <description>Encryption tool</description>
    <url>https://github.com/MasterFlomaster1/JFXCrypto</url>

    <licenses>
        <license>
            <name>Apache License 2.0</name>
            <url>https://raw.githubusercontent.com/MasterFlomaster1/JFXCrypto/master/LICENSE</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <developers>
        <developer>
            <id>MasterFlomaster1</id>
            <name>MasterFlomaster1</name>
        </developer>
    </developers>
    <modules>
        <module>core</module>
        <module>gui</module>
    </modules>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <javafx.version>23.0.1</javafx.version>
        <ikonli.version>12.3.1</ikonli.version>
        <javafx.maven.plugin.version>0.0.8</javafx.maven.plugin.version>
        <sass.version>1.54.4</sass.version>

        <app.name>JFXCrypto</app.name>
        <app.version>4.5.0</app.version>
        <app.launcher>dev.masterflomaster1.jfxc.Start</app.launcher>

        <build.dependenciesDir>${project.build.directory}${file.separator}dependencies</build.dependenciesDir>
        <build.platformModulesDir>${project.build.directory}${file.separator}platform-modules</build.platformModulesDir>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>1.18.34</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.jetbrains</groupId>
                <artifactId>annotations</artifactId>
                <version>24.1.0</version>
            </dependency>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-api</artifactId>
                <version>2.0.16</version>
            </dependency>
            <dependency>
                <groupId>ch.qos.logback</groupId>
                <artifactId>logback-classic</artifactId>
                <version>1.5.12</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <profiles>
        <profile>
            <id>dev</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.openjfx</groupId>
                        <artifactId>javafx-maven-plugin</artifactId>
                        <configuration>
                            <options>
                                <option>-Datlantafx.mode=dev</option>
                            </options>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>windows-active</id>
            <activation>
                <os>
                    <family>windows</family>
                </os>
            </activation>
            <properties>
                <platform>win</platform>
            </properties>
        </profile>
        <profile>
            <id>release</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <build>
                <plugins>
                    <!-- package project sources -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-source-plugin</artifactId>
                        <version>3.3.1</version>
                        <executions>
                            <execution>
                                <id>attach-source</id>
                                <phase>compile</phase>
                                <goals>
                                    <goal>jar-no-fork</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
    
</project>